[package]
name = "gateway-demo-frontend"
version = "0.1.0"
edition = "2021"
readme = "README.md"

[dependencies]
futures = { workspace = true }
gloo-net = { workspace = true }
gloo-timers = { workspace = true }
js-sys = { workspace = true }
yew = { workspace = true, features = ["csr"] }
